language: java
jdk:
    - openjdk7
    - oraclejdk8
sudo: false
before_install:
    - cp ./etc/settings.xml ~/.m2/
    - cp ./etc/onFailure.sh  ~/
    - cp ./etc/onSuccess.sh  ~/
    - chmod 777 ~/onFailure.sh
    - chmod 777 ~/onSuccess.sh
script:
    - mvn -B clean verify
after_failure: ~/onFailure.sh
after_success: ~/onSuccess.sh
notifications:
    email: false
    irc:
        channels:
            - chat.freenode.net#lightblue
    on_success: always
env:
    global:
        - secure: OMLZifSAjy3luFVxnDxEdeyzqfGaP9H1HTJIaxWASTBNUHnbZaqPQtjIXe8KjrPgqunLofXa/lF1SWe+PzgZMgSJWvCYI9YN7lW908m8egroYFe6hITJvBABY6jkcGc50b9F4PHe3YAPtZdX2FSlInBVlskXMXeCV2bql3+SIcD3DL9N2w/MfcZKkJSG3ZqYooMoGgmH/fbxLJ1KmRV0qhOBATTX0N3k+WU2ChCoRI3AbKZLxuDS/TUDjutOponTeD2v0YLclwYL5QW1uYjqOYsX/Tsw0U3ajZ8MHODsSVKJR7cIsq9Qmyxpx03wAnjL+TUygGG9cggFeR9dvWH15/ZgJFI4oeZZVIHam8Spv1LXCpovSTnN7p/TscKFZPiDqcBUloJrrskLst/x40mnHU0Ami4oQzRUtvFSXm+jksOnaJzLBxqXrqpmPjFZWAepoESJpyVpDXTsqhFYZ1IRaXNzEDWjFD8ZJEy+5cwODT75ZxSW0QX9CHmACEfFrgdh28vHHwBK+sAQLGi+Yt5MISblO0/1MTpeEygk8XuMz0axYAqepulqkrd04+qp8abda5K2u0dqF0ao0JiDKsNVw4Ca+TJIOyKFU2hqblkj6rDADyU3FQfn/HWmoqypoWztz2LnPsM4uVTW9cdiRvxzoOzNI874RhvuJL5i/p6Y0Qs=
        - secure: qNpqCkFaXQ9FvfkFix3hCot49TVtCe6wVJ1cp7KzQeZFTyhYuOGEFxBmm58bUCt1tXhdRSyYtA+uv+WbvvWPkx7Xmqz3jngdaK2mBBR9fb82Vh97fCY/1SQ/rKmdto5AL08vRxsXt856dvK29ONgybtqiK9Y5+KYnYzMu551cj8gO55Q2e34AWzxb8s40fyIQ5JsrkluFoaBiyv7EmB0cjn6DBzzF7R6Jqp0zwc1zL4zR/bfZKcw28XdreAuhn65KD2GnmEQRJB8gB3SpkMZmxvkyqZx0ebYC9K8sRo9CuerP/PuLLS/xkB27EyNZgePYTJt1w/g01rQdTbC6fGaLY2uXYaIXfJZNBkTL5U0mEiGa4q0VrhLkoFQ3bmuGxMs5/0HkFnOceuxOQbwRy588Sg36BR8PDJ3/XaP0qOYcmpvsVnOb5fWsqY5xkQA7mPPHpbdV22h+QiAfNuzC4w1NuHDmgvysz+ltmxLyNt+DzwycNlkrJIO/bR4hDpK7mZhUOy8Ard2PTwkCRaEGTy80XNQt4ByI/jxOgTsEq2pCtgtFDxBfvAQR2waUaoblj73B4MtVkE0urS2aTwrTjUNv5x1gApsv9JOF/TBRb33OjOHYEC8vnyMhiVm1YpKCOniru28FhqiTF+8Xy1CpbihVj8aQzMfnx+R8daEmwq04po=
sudo: false
